export const ROOT_URL = 'http://lottoback-rorturtola.c9users.io';
//export const ROOT_URL = 'http://kwanga.ml:8080';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CURRENT_USER = 'CURRENT_USER';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const ROOT_CHANGED = 'ROOT_CHANGED';
export const CUSTOMER_TOKEN_SUCCESS = 'CUSTOMER_TOKEN_SUCCESS';
export const CHANGE_ACCESS_FILTER = 'CHANGE_ACCESS_FILTER';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';
export const RESET_CUSTOMER_TOKEN = 'RESET_CUSTOMER_TOKEN';
export const FETCH_USER_LOTTO_SUCCESS = 'FETCH_USER_LOTTO_SUCCESS';
export const PLAY_LOTTO_SUCCESS = 'PLAY_LOTTO_SUCCESS';
export const FETCH_LOTTO_WIN_SUCCESS = 'FETCH_LOTTO_WIN_SUCCESS';
export const ADD_LOTTO_WIN_SUCCESS = 'ADD_LOTTO_WIN_SUCCESS';
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS';

export const MEGA_MILLIONS_RESULT_SUCCESS = 'MEGA_MILLIONS_RESULT_SUCCESS';
export const FETCH_LAST_MEGA_MILLIONS_RESULT_SUCCESS = 'FETCH_LAST_MEGA_MILLIONS_RESULT_SUCCESS';
export const EURO_MILLIONS_RESULT_SUCCESS = 'EURO_MILLIONS_RESULT_SUCCESS';
export const FETCH_LAST_EURO_MILLIONS_RESULT_SUCCESS = 'FETCH_LAST_EURO_MILLIONS_RESULT_SUCCESS';
export const EURO_MILLIONS_GO_RESULT_SUCCESS = 'EURO_MILLIONS_GO_RESULT_SUCCESS';
export const FETCH_LAST_EURO_MILLIONS_GO_RESULT_SUCCESS = 'FETCH_LAST_EURO_MILLIONS_GO_RESULT_SUCCESS';

